"""empty message

Revision ID: c5d1585a09cd
Revises: 91dddba13164
Create Date: 2024-03-13 16:19:29.978643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d1585a09cd'
down_revision = '91dddba13164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rum_user_token', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rum', schema=None) as batch_op:
        batch_op.drop_column('rum_user_token')

    # ### end Alembic commands ###
